### PR TITLE
Add reset methods for each option

### PR DESCRIPTION
**Pull request by melissalinkert**
Corresponds to https://github.com/glencoesoftware/bioformats2raw/pull/219

### CODE REVIEW

**Review by DavidStirling — COMMENTED** [review]
Changes look fine, though between this and the getters/setters could I check whether the `tileQueue` size limit should be being adjusted when maxWorkers is changed? It currently looks like this is only set when the class is initialised.

https://github.com/glencoesoftware/raw2ometiff/blob/6cd57d79dd3a3e75814c9c766f74d411416cf76f/src/main/java/com/glencoesoftware/pyramid/PyramidFromDirectoryWriter.java#L150-L152

**Comment by melissalinkert** [comment]
> Changes look fine, though between this and the getters/setters could I check whether the `tileQueue` size limit should be being adjusted when maxWorkers is changed? It currently looks like this is only set when the class is initialised.

Good catch; a0dafc7 should reset `tileQueue` to match `maxWorkers` when the setter or resetter actually changes the value of `maxWorkers`.

**Comment by DavidStirling** [comment]
I'm a bit lost here now, how are we meant to reset values if not using the CLI?

**Comment by melissalinkert** [comment]
@DavidStirling: sorry, the build was failing quietly here due to a merge conflict, so it's likely you're seeing `MissingParameterException` because the relevant default value changes weren't included. f996b88 fixes the conflict and builds now pass, so see if it works after updating?

**Review by DavidStirling — APPROVED** [review]
Working now, thanks!

**Review by sbesson — CHANGES_REQUESTED** [review]
Thanks @melissalinkert. Looks good to me and happy to move forward with this strategy together with https://github.com/glencoesoftware/bioformats2raw/pull/226 in the upcoming `0.6.0` release of `raw2ometiff`

Before merging, could we add a simple `testResetOptions` unit test demonstrating and covering the usage of the API to reset options similarly to https://github.com/glencoesoftware/bioformats2raw/pull/226/files#diff-3bf686322477afd2500c0b42697eb037dd07ae3fc65e17ece2facd25bf5c6081R1997-R2035?

**Pull request merged**
