### PR TITLE
Add note about `--quality` option

### PR DESCRIPTION
**Pull request by melissalinkert**
/cc @muhanadz @mgheirat @DavidStirling @erindiel

### CODE REVIEW

**Review by DavidStirling — APPROVED** [review]
LGTM. Do we have a list of accepted compression types somewhere?

**Review by muhanadz — APPROVED** [review]
This PR adds clarity and important information about the range and values for the `--quality` flag used with compression that was missing before. The explanation is thorough and straightforward with good examples and starting value for users.

Looks good.

**Comment by muhanadz** [comment]
@DavidStirling As far as I know the only way to see the list of accepted compression is with `raw2ometiff --help`.
```
--compression=<compression>
                         Compression type for output OME-TIFF file
                           (Uncompressed, LZW, JPEG-2000, JPEG-2000 Lossy,
                           JPEG, zlib; default: LZW)
```
Maybe we should open another PR, either listing the compression types or adding the output of `raw2ometiff --help`?

**Comment by mgheirat** [comment]
Looks good to me. Very useful info. 
@melissalinkert could you point us to the code where the --quality option is being used in the JPEG2000 lossy params setting?

**Comment by mgheirat** [comment]
Thank you very much @melissalinkert for the detailed sequence of pointers!

**Review by muhanadz — APPROVED** [review]
LGTM!

**Pull request merged**
